- a/public/index.html
> 로그인 기능 구현 완료

- public/signup.html
> 회원가입 만들었습니다

- README.md
> [Docs]-README.md 작성 중

- package-lock.json
- package.json
프로젝트 시작을 위한 필수 node 패키지 설치
feature-#26-package.json 업데이트
> [Chore]-필요 패키지 설치

- src/API/loginAPI.js
- src/API/signUpAPI.js
- src/App.js
- src/Components/Login/Login.jsx
- src/Components/SignUp/SignUp.jsx
- src/index.js
> Feature #24 로그인구현

- README.md
- src/API/loginAPI.js
- src/Components/Chat/ChattingList.jsx
- src/Components/Chat/ChattingRoom.jsx
- src/Components/Commons/Footer.jsx
- src/Components/Commons/Header.jsx
- src/Components/Login/Login.jsx
- src/Components/Main/PostDetail.jsx
- src/Components/Main/PostList.jsx
- src/Components/Main/SwitchMode.jsx
- src/Components/Profile/MyPostList.jsx
- src/Components/Profile/Profile.jsx
- src/Components/Profile/Recruit.jsx
- src/Components/SignUp/SignUp.jsx
- src/Pages/ChattingListPage.jsx
- src/Pages/FollowDetailPage.jsx
- src/Pages/MainFeedPage.jsx
- src/Pages/ProfilePage.jsx
- src/Pages/SignUpPage.jsx
- src/Pages/WritePage.jsx
- src/Router/Router.jsx
axios 코드 개편 및 내용 확인
#37-recoil 적용 어렵습니다... localstorage이용하는게 정신적으로 좋아보입니다.
> [Feat]-파일 내용 삽입 및 axios 코드 개편

- src/Components/Commons/Footer.jsx
- src/Router/Router.jsx
#63 Footer active 에러 해결 및 관련 라우터 분리
1. active 속성이 styled components에만 적용되도록 active => $active로 변경 (Dom까지 전달되면 경고 발생)
2. 라우터 추가 페이지: ChattingList, Write, Profile
> Feature #43 footer active 에러 해결

- src/Components/Commons/Footer.jsx
- src/Components/Commons/Header/HeaderStyle.jsx
- src/Components/Main/PostItem/PostItemStyle.jsx
- src/Pages/MainFeedPage.jsx
Header, Footer 상하단에 고정하기 위해 디자인 변경
#44 #43
position: fixed;
top: 0;
left: 0;
width: 100%;
z-index: 1000;
box-sizing: border-box;
#50 
flex: 1 auto;
overflow-y: auto;
> Feature #43 Header, Footer, PostItem 디자인 수정

- src/Components/Commons/Error404.jsx
> [Style]-css 수정

- src/Components/Main/PostDeatilModal/PostDetailModal.jsx
- src/Components/Main/PostDeatilModal/PostDetailStyle.jsx
- src/Components/Main/PostItem/PostItem.jsx
- src/Components/Main/PostItem/PostItemStyle.jsx
- src/Pages/MainFeedPage.jsx
> Feature #68 main feed모달구현

- src/API/loginAPI.js
- src/Components/Login/Login.jsx
로그인에 실패해도 로컬 스토리지에 토큰값이 남아있는 경우, 로그인이 되어버리는 버그 픽스.
> Feature #82 로그인 버그픽스 

- src/Components/Chat/ChattingRoom.jsx
- src/Components/Commons/Header/HeaderStyle.jsx
- src/Router/Router.jsx
- src/styles/GlobalStyled.js
> Feat #80 chattingroom 구현

- package-lock.json
- package.json
- src/API/emailValidAPI.js
- src/API/loginAPI.js
- src/API/signUpAPI.js
- src/Components/Login/Login.jsx
- src/Components/Login/LoginStyle.jsx
- src/Components/SignUp/SetProfile.jsx
- src/Components/SignUp/SignUp.jsx
- src/Components/SignUp/SignUpStyle.jsx
회원가입 할 때 정상적인 메시지가 뜨지 않거나, 제대로 가입되지 않는 현상 수정
- #41
> Feature #84 회원가입 버그픽스

- src/API/commentAPI.js
- src/API/commentWriteAPI.js
- src/Components/Main/PostDeatilModal/PostDetailModal.jsx
- src/Components/Main/PostDeatilModal/PostDetailStyle.jsx
- src/Components/Main/PostItem/PostItem.jsx
- src/Components/Main/PostItem/PostItemStyle.jsx
- src/Functional/DateFunction.js
- src/Pages/MainFeedPage.jsx
- src/Store/Store.js
- src/index.js
PostDetailModal 기능 구현 및 디자인 수정
#68 디자인 작업 수정
> Feature #75 post modal기능 구현

- src/Components/Chat/ChattingDummy.js
- src/Components/Chat/ChattingList.jsx
- src/Components/Chat/ChattingListStyle.jsx
- src/Pages/ChattingListPage.jsx
> [Feat]-채팅리스트 더미데이를 통해 개발 완료

- src/Components/Commons/Footer.jsx
Footer 버튼 전환 버그 수정
useState로 active가 초기화되는 문제였음 
useLocation으로 해결
> [Fix]-Footer 버튼 전환 버그 수정

- src/Pages/WritePage.jsx
> Feature #98 writepage 기능 구현

- src/API/followAPI/followerAPI.js
- src/API/followAPI/unFollowAPI.js
- src/Components/Profile/FollowList/FollowList.jsx
> Feature #103 프로필상세 페이지 개선

- src/API/searchUserAPI.js
- src/Components/Commons/Header/Header.jsx
- src/Components/Commons/Header/HeaderStyle.jsx
- src/Components/Search/Search.jsx
- src/Components/Search/SearchStyle.jsx
- src/Pages/SearchPage.jsx
- src/Store/Store.js
> Feature #110 검색 기능구현

- src/API/emailValidAPI.js
- src/API/followAPI/followAPI.js
- src/API/followAPI/followerAPI.js
- src/API/followAPI/unFollowAPI.js
- src/API/followingPostAPI.js
- src/API/loginAPI.js
- src/API/myInfoAPI.js
- src/API/signUpAPI.js
- src/Components/Commons/Header/Header.jsx
- src/Components/Profile/FollowList/FollowList.jsx
- src/Components/Profile/FollowList/FollowListStyle.jsx
- src/Components/Profile/ProfileDetail/ProfileDetail.jsx
- src/Pages/FollowDetailPage.jsx
- src/Router/Router.jsx
> Feature #117 코드개선

- src/Components/Write/GameRecruitPost.jsx
- src/Components/Write/Post.jsx
게시글 작성 및 게임 모집 작성글 이미지 오류 수정
#115 기능 조금 수정하였습니다.
> [Fix]-게시글 작성 및 게임 모집 작성글 이미지 오류 수정

- src/API/profileFixAPI.js
- src/API/removeMyPostAPI.js
- src/Components/Profile/ProfileFix/ProfileFix.jsx
- src/Components/Profile/ProfileFix/ProfileFixStyled.jsx
- src/Components/Sign/SignUp/SetProfile.jsx
- src/Router/Router.jsx
게시글 삭제 기능 구현, 이미지 업로드 관련 코드 전부 수정
#122 코드상 문제로 게시글 삭제 API만 구현 추후 상의
> Feature #122 게시글 삭제 기능 구현

- src/Components/Commons/Footer.jsx
- src/Components/Profile/FollowList/FollowList.jsx
- src/Components/Profile/ProfileDetail/ProfileDetail.jsx
- src/Components/Profile/ProfileDetail/ProfileDetailStyle.jsx
- src/Components/Sign/SignUp/SetProfile.jsx
- src/Components/Sign/SignUp/SignUpStyle.jsx
- src/Pages/ProfilePage.jsx
- src/Store/Store.js
> Feature #119 회원가입 모달창

- src/API/removeMyPostAPI.js
- src/API/userPostListAPI.js
- src/Components/Commons/Footer.jsx
- src/Components/Profile/MyPostList/MoreModal/MoreModal.jsx
- src/Components/Profile/MyPostList/MoreModal/MoreModalStyle.jsx
- src/Components/Profile/MyPostList/MyPostDetailModal/MyPostDetailModal.jsx
- src/Components/Profile/MyPostList/MyPostDetailModal/MyPostDetailModalStyle.jsx
- src/Components/Profile/MyPostList/MyPostList.jsx
- src/Components/Profile/MyPostList/MyPostListStyle.jsx
- src/Components/Profile/ProfileDetail/ProfileDetail.jsx
- src/Pages/ProfilePage.jsx
- src/Store/Store.js
myPostList 상세모달 구현
- postDetailModal 구조 가져옴
- 기본 구조에 페이지별 modal 로직 추가
- myPostList, 상세 모달 두 곳에서 삭제 가능
코드 정리는 추후에 ...........................꼭........................하겠습니다
> Feature #128 mypostlist 상세모달 및 게시글 삭제하기 구현

- src/Components/Profile/MyPostList/MoreModal/MoreModal.jsx
- src/Components/Profile/MyPostList/MyPostDetailModal/MyPostDetailModal.jsx
- src/Components/Profile/MyPostList/MyPostList.jsx
- src/Components/Profile/MyPostList/MyPostListStyle.jsx
- src/Pages/ProfilePage.jsx
profilePage 모달 관련 버그픽스
- 게시글 상세보기 모달과, 신고삭제 모달 관련 이름들을 직관적으로 구분할 수 있도록 정리
-  postModal, OptionModal로 적용 (isPostModaVisible, isOptionModalVisible)
#128
> Feature #132 profilePage 모달 버그픽스

- src/Components/Profile/Recruit/Recruit.jsx
- src/Components/Profile/Recruit/RecruitStyle.jsx
모집중인 게임 모달창이 이미지 해상도가 너무 클 때 이미지가 잘려나가는 현상 수정
> [Fix]-모집중인 게임 모달창이 이미지 해상도가 너무 클 때 이미지가 잘려나가는 현상 수정

- src/Components/Main/PostDeatilModal/PostDetailModal.jsx
- src/Components/Main/PostItem/PostItem.jsx
- src/Components/Profile/Recruit/Recruit.jsx
- src/Components/Search/Search.jsx
검색 기능 이미지 수정 및 모집 중인 글 기능 수정
.
> Feature #137 검색 기능 이미지 수정 및 모집 중인 글 기능 수정

- src/Components/Main/PostDeatilModal/PostDetailModal.jsx
- src/Components/Main/PostDeatilModal/PostDetailStyle.jsx
- src/Components/Main/PostItem/PostItem.jsx
- src/Components/Main/PostItem/PostItemStyle.jsx
- src/Components/Search/Search.jsx
- src/Functional/isValidImageFunction.js
> Feature #146 mainfeed 디자인 수정 작업

- src/Components/Commons/List/CommonPostList.jsx
- src/Components/Commons/List/CommonPostListStyle.jsx
- src/Components/Main/PostItem/PostItem.jsx
- src/Components/Main/PostList.jsx
- src/Components/Profile/MyPostList/MyPostList.jsx
- src/Functional/isValidImageFunction.js
- src/Store/Store.js
mainfeed 및 프로필 컴포넌트 통합 작업
#50 #45 이제야 합쳤습니다....
> Feature #151 mainfeed 및 프로필 컴포넌트 통합 작업

- src/Components/Sign/Login/LoginStyle.jsx
- src/Components/Sign/SignUp/SignUpStyle.jsx
> Feature #150 로그인페이지 다크테마 적용

- src/Components/Commons/DetailModal/CommonDetailModal.jsx
- src/Components/Commons/DetailModal/CommonDetailModalStyle.jsx
- src/Components/Profile/MyPostList/MoreModal/MoreModal.jsx
- src/Components/Profile/MyPostList/MyPostDetailModal/MyPostDetailModal.jsx
- src/Pages/MainFeedPage.jsx
- src/Pages/ProfilePage.jsx
MainFeed PostDetail, Profile PostDetai 통합
기존 데이터의 렌더링 중 잠깐 뜨는 이슈
merge가 안되는 관계로 새로 작업
> Feature #153 postdetailmodal 융합

- src/Components/Commons/DetailModal/CommonDetailModal.jsx
- src/Components/Commons/DetailModal/CommonDetailModalStyle.jsx
- src/Components/Main/PostDeatilModal/PostDetailModal.jsx
- src/Components/Main/PostDeatilModal/PostDetailStyle.jsx
- src/Components/Main/PostItem/PostItemStyle.jsx
- src/Components/Profile/MyPostList/MyPostDetailModal/MyPostDetailModal.jsx
- src/Components/Profile/MyPostList/MyPostDetailModal/MyPostDetailModalStyle.jsx
Modal 디자인 이식 완료
#135 Modal 클릭 시, 뒤의 배경이 조금 씩 움직이는 현상 발견
> [Style]-Modal 디자인 이식 완료

- src/Components/Write/GameRecruitPost.jsx
- src/Components/Write/Post.jsx
- src/Components/Write/PostEdit.jsx
- src/Components/Write/PostEditStyle.jsx
- src/Components/Write/Write.jsx
- src/styles/GlobalStyled.js
> Feature #144 게시 글 작성/수정 반응형 구현

- src/Components/Main/HomeNoFeed.jsx
- src/Components/Profile/FollowList/FollowListStyle.jsx
- src/Components/Profile/ProfileFix/ProfileFix.jsx
- src/Components/Profile/ProfileFix/ProfileFixStyled.jsx
> [Style]-디자인 수정 작업

- src/Components/Commons/Alert/Alert.jsx
- src/Components/Commons/Alert/AlertStyle.jsx
- src/Components/Commons/DetailModal/CommonDetailModal.jsx
- src/Components/Commons/DetailModal/CommonDetailModalStyle.jsx
- src/Components/Write/GameRecruitPost.jsx
- src/Components/Write/Post.jsx
- src/Components/Write/PostEdit.jsx
- src/Components/Write/Write.jsx
- src/Pages/ProfilePage.jsx
- src/Store/Store.js
alert창 만들기
#109 submit 전송시, 이미지 깨지는 현상
> Feature #173 alert창 만들기

- src/Components/Profile/ProfileFix/ProfileFix.jsx
- src/Components/Profile/Recruit/Recruit.jsx
- src/Components/Profile/Recruit/RecruitEdit/RecruitEdit.jsx
- src/Components/Write/GameRecruitPost.jsx
- src/Components/Write/Post.jsx
- src/Components/Write/PostEdit.jsx
- src/Components/Write/Write.jsx
> Feature #176 modal창 삽입 및 기타 디자인 수정 작업

- src/Components/Commons/DetailModal/CommonDetailModalStyle.jsx
> [Design]-댓글 wrapper height 수정

- src/Components/Chat/ChattingList.jsx
- src/Components/Chat/ChattingListStyle.jsx
- src/Components/Chat/ChattingRoomStyle.jsx
- src/Pages/ChattingListPage.jsx
> [Design]-채팅페이지 디자인 수정

- src/API/emailValidAPI.js
- src/API/followAPI/followListAPI.js
- src/API/followAPI/followingAPI.js
- src/API/followAPI/unFollowAPI.js
- src/API/followingPostAPI.js
- src/API/gameRecruitAPI/gameRecruitAPI.js
- src/API/gameRecruitAPI/gameRecruitDeleteAPI.js
- src/API/gameRecruitAPI/gameRecruitEditAPI.js
- src/API/gameRecruitAPI/gameRecruitListAPI.js
- src/API/gameRecruitAPI/ifProfileEditedAPI.js
- src/API/gameRecruitAPI/joinRecruitAPI.js
- src/API/gameRecruitAPI/leaveRecruitAPI.js
- src/API/loginAPI.js
- src/API/masterTokenAPI.js
- src/API/postAPI.js
- src/API/postEditAPI.js
- src/API/reportCommentAPI.js
- src/API/signUpAPI.js
- src/Components/Commons/Header/Header.jsx
- src/Components/Commons/List/CommonPostListStyle.jsx
- src/Components/Profile/ProfileDetail/ProfileDetail.jsx
- src/Components/Profile/ProfileFix/ProfileFix.jsx
- src/Components/Profile/Recruit/Recruit.jsx
- src/Components/Profile/Recruit/RecruitEdit/RecruitEdit.jsx
- src/Components/Profile/Recruit/RecruitStyle.jsx
- src/Pages/FollowDetailPage.jsx
- src/Pages/ProfilePage.jsx
- **콘솔창에 뜨는 isHorverd와 isMyProfile 관련 에러(빨간색)는 MyPostList 내부의 isHoverd와 isMyProfile 때문에 발생합니다. 작동원리를 몰라서 못고쳤습니다. MyPostList하신 분이 확인해주시면 감사하겠습니다.**
> Feature #184 버그픽스 및 디자인개선

- src/Components/Profile/FollowList/FollowListStyle.jsx
- src/Components/Profile/ProfileDetail/ProfileDetail.jsx
- src/Components/Search/SearchStyle.jsx
- src/Pages/ProfilePage.jsx
- src/Store/Store.js
> Feature #189 오류 수정 작업

- src/Components/Profile/Recruit/RecruitEdit/RecruitEdit.jsx
- src/Components/Profile/Recruit/RecruitEdit/RecruitEditStyle.jsx
- src/Components/Write/WriteStyle.jsx
> Feature #144 게시 / 모집 디자인 수정

- src/Components/Profile/Recruit/RecruitEdit/RecruitEdit.jsx
- src/Components/Profile/Recruit/RecruitEdit/RecruitEditStyle.jsx
- src/Components/Profile/Recruit/RecruitStyle.jsx
- src/Components/Write/GameRecruitPost.jsx
- src/Components/Write/Post.jsx
- src/Components/Write/PostEdit.jsx
- src/Components/Write/PostEditStyle.jsx
- src/Components/Write/WriteStyle.jsx
> Feature #192 오류 수정 작업

- src/Components/Profile/Recruit/RecruitEdit/RecruitEdit.jsx
- src/Components/Profile/Recruit/RecruitEdit/RecruitEditStyle.jsx
- src/Components/Write/GameRecruitPost.jsx
- src/Components/Write/Post.jsx
- src/Components/Write/PostEdit.jsx
- src/Components/Write/PostEditStyle.jsx
- src/Components/Write/WriteStyle.jsx
> [Style]-게시글/수정/모집 디자인 수정

- src/Components/Commons/List/CommonPostListStyle.jsx
> [Style]-피드 border 수정

- src/Components/Chat/ChattingDummy.js
- src/Components/Chat/ChattingRoomStyle.jsx
- src/Components/Commons/DetailModal/CommonDetailModalStyle.jsx
- src/Components/Commons/List/CommonPostList.jsx
- src/Components/Commons/List/CommonPostListStyle.jsx
- src/Components/Write/GameRecruitPost.jsx
- src/Components/Write/Post.jsx
- src/Components/Write/PostEdit.jsx
- src/Components/Write/PostEditStyle.jsx
- src/Components/Write/WriteStyle.jsx
> Feature #202 코드 수정작업

- src/Components/Commons/DetailModal/CommonDetailModalStyle.jsx
상세모달 content, comment 반응형 높이 수정
> Feature #135 상세모달 content,comment 반응형 높이 수정

- README.md
> [Docs]-README 수정 작업 완료

- README.md
> readme 수정본 merge
